// Style: Sessiz Ay Takvimi — seçenekler kısa, taranabilir ve tıbbi teşhis dili içermez.
import type { Energy, Flow, MoodKey } from "./symptom.types";

type Option = [string, string];
export const flowOptions: Array<[Flow, string]> = [["none", "Yok"], ["spotting", "Lekelenme"], ["light", "Hafif"], ["medium", "Orta"], ["heavy", "Yoğun"]];
export const energyOptions: Array<[Energy, string]> = [["very_low", "Çok düşük"], ["low", "Düşük"], ["normal", "Normal"], ["high", "Yüksek"], ["very_high", "Çok yüksek"]];
export const moodOptions: Array<[MoodKey, string]> = [["happy", "Mutlu"], ["calm", "Sakin"], ["energetic", "Enerjik"], ["motivated", "Motivasyonu yüksek"], ["sensitive", "Hassas"], ["emotional", "Duygusal"], ["stressed", "Stresli"], ["anxious", "Kaygılı"], ["sad", "Üzgün"], ["irritable", "Sinirli"], ["unfocused", "Odaklanmakta zorlanıyor"]];
export const symptomGroups: Array<{ title: string; items: Option[] }> = [{ title: "Ağrı", items: [["headache", "Baş ağrısı"], ["migraine", "Migren"], ["back_pain", "Bel ağrısı"], ["pelvic_pain", "Pelvik ağrı"], ["breast_tenderness", "Göğüs hassasiyeti"]] }, { title: "Sindirim", items: [["bloating", "Şişkinlik"], ["constipation", "Kabızlık"], ["diarrhea", "İshal"], ["nausea", "Mide bulantısı"], ["gas", "Gaz"]] }, { title: "Cilt", items: [["acne", "Akne"], ["oily_skin", "Yağlı cilt"], ["dry_skin", "Kuru cilt"]] }, { title: "Uyku", items: [["good_sleep", "İyi uyudum"], ["insomnia", "Uykusuzluk"], ["woke_often", "Sık uyandım"], ["overslept", "Çok uyudum"]] }, { title: "Genel", items: [["fatigue", "Yorgunluk"], ["dizziness", "Baş dönmesi"], ["increased_appetite", "İştah artışı"], ["decreased_appetite", "İştah azalması"], ["sugar_craving", "Tatlı isteği"], ["concentration", "Konsantrasyon zorluğu"]] }, { title: "Vajinal / döngü", items: [["discharge", "Akıntı"], ["dryness", "Kuruluk"]] }];
export const labelFor = (key: string) => symptomGroups.flatMap((group) => group.items).find((item) => item[0] === key)?.[1] ?? moodOptions.find((item) => item[0] === key)?.[1] ?? key;
